server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: buscar-cep-service
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cidades?useTimezone=true&serverTimezone=UTC
    username: root
    password: henrique123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    url: jdbc:mysql://localhost:3306/cidades?useTimezone=true&serverTimezone=UTC
    user: root
    password: henrique123
springdoc:
  show-actuator: true
  api-docs:
    path: buscar-cep-service/v3/api-docs
