server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: produtos-service
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/produtos_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: henrique123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: produtos_service
    user: root 
    password: henrique123
springdoc:
  show-actuator: true
  api-docs:
    path: produtos-service/v3/api-docs
