server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: compra-service
        uri: lb://compra-service
        predicates:
        - Path=/comprar/**
      - id: buscar-cep-service
        uri: lb://buscar-cep-service
        predicates:
        - Path=/buscar/**
      - id: produtos-service
        uri: lb://produtos-service
        predicates:
        - Path=/produtos/**
      - id: openapi
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs         
        
        
        

 
      