server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
  ratelimiter:
    instances:
      default: 
        limit-for-period: 2  #limite por período
        limit-refresh-period: 10s #tamanho do período // a cada 10s só posso fazer 2 requisições
  retry:
    instances:
      default:
       max-attempts: 5
       wait-duration: 1s
spring:
  application:
    name: compra-service
  sleuth:
    sampler:
      probability: 1.0
  #zipkin:
    #base-url: http://localhost:6789
springdoc:
  show-actuator: true
  api-docs:
    path: compra-service/v3/api-docs

