name: Continuous Integration with Github
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
         java-version: '17'
         distribution: 'adopt'
         
      - name: Build Eureka Server Container Image
        working-directory: ./Docker/02-eureka-server
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build API Gateway Container Image
        working-directory: ./Docker/02-api-gateway
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Buscar CEP Microsservice JAR
        working-directory: ./Docker/02-buscar-cep-service
        run: mvn clean package -DskipTests
        
      - name: Build Listar Produtos Microsservice JAR
        working-directory: ./Docker/02-listagem-de-produtos
        run: mvn clean package -DskipTests
        
      - name: Build Compra Microsservice Container Image
        working-directory: ./Docker/02-compra-service
        run: mvn spring-boot:build-image -DskipTests
      
      - name: Docker Compose Build
        working-directory: ./Docker
        run: docker-compose build
        
      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{secrets.DOCKER_USERNAME}}/eureka-server:0.0.1-SNAPSHOT ${{secrets.DOCKER_USERNAME}}/eureka-server:${{github.run_id}}
          docker tag ${{secrets.DOCKER_USERNAME}}/api-gateway:0.0.1-SNAPSHOT ${{secrets.DOCKER_USERNAME}}/api-gateway:${{github.run_id}}
          docker tag ${{secrets.DOCKER_USERNAME}}/buscar-cep-service:latest ${{secrets.DOCKER_USERNAME}}/buscar-cep-service:${{github.run_id}}
          docker tag ${{secrets.DOCKER_USERNAME}}/listagem-de-produtos:latest ${{secrets.DOCKER_USERNAME}}/listagem-de-produtos:${{github.run_id}}
          docker tag ${{secrets.DOCKER_USERNAME}}/compra-service:0.0.1-SNAPSHOT ${{secrets.DOCKER_USERNAME}}/compra-service:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/eureka-server:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/api-gateway:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/buscar-cep-service:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/listagem-de-produtos:${{github.run_id}}
          docker push ${{secrets.DOCKER_USERNAME}}/compra-service:${{github.run_id}}
          
          
          
          
          
          
         
          


   
