name: Continuous Integration with Github
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
         java-version: '17'
         distribution: 'adopt'
         
      - name: Build Eureka Server Container Image
        working-directory: ./Docker/02-eureka-server
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Compra Microsservice Container Image
        working-directory: ./Docker/02-compra-service
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build API Gateway Container Image
        working-directory: ./Docker/02-api-gateway
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Buscar CEP Microsservice JAR
        working-directory: ./Docker/02-buscar-cep-service
        run: mvn clean package -DskipTests
        
      - name: Build Listar Produtos Microsservice JAR
        working-directory: ./Docker/02-listagem-de-produtos
        run: mvn clean package -DskipTests
      
      - name: Docker Compose Build
        working-directory: ./Docker
        run: docker-compose build
